gfuncionarios/urls.py
from django.urls import path
from .views import *

urlpatterns = [
	path('lista/funcionario/index.html',index,name='lista-funcionarios'),

	path('funcionarios-data/', funcionarios_data, name='funcionarios_data'),  # New data URL

	path('registar/funcionario/index.html?register=True',RegistaNovoFuncionario,name='RegistaNovoFuncionario'),
	path('detalho/funcionario/index.html?fid=<str:idf>',DetailFuncionario,name='DetailFuncionario'),
	path('alterar/funcionario/index.html?fid=<str:id>&atualizar=True',AtualizarFuncionario,name='AtualizarFuncionario'),
	path('desabilitar/funcionario/index.html?fid=<str:id>&desabilitar=True',DesabilitarFuncionario,name='DesabilitarFuncionario'),
	

	path('lista/colocacao/funcionario/index.html?fid=<str:id>&lista=True',DetalhoFuncionarioListaColocacao,name='DetalhoFuncionarioListaColocacao'),
	path('registar/colocacao/funcionario/index.html?fid=<str:id>&register=True',DetalhoFuncionarioRegistarColocacao,name='DetalhoFuncionarioRegistarColocacao'),
	path('alterar/colocacao/funcionario/index.html?fid=<str:id>&idfc=<str:idfc>&alterar=True',UpdateColocacao,name='UpdateColocacao'),
	path('desabilitar/colocacao/funcionario/index.html?fid=<str:id>&idfc=<str:idfc>&desabilitar=True',DesabilitarColocacao,name='DesabilitarColocacao'),
	
	path('lista/nao-exercicio/funcionario/index.html?fid=<str:id>&lista=True',DetalhoFuncionarioListaNaoExercicio,name='DetalhoFuncionarioListaNaoExercicio'),
	path('registar/nao-exercicio/funcionario/index.html?fid=<str:id>&registar=True',DetalhoFuncionarioRegistarFNExercicio,name='DetalhoFuncionarioRegistarFNExercicio'),
	path('registar/nao-exercicio/funcionario/index.html?fid=<str:id>&idfne=<str:idfne>&alterar=True',UpdateFNExercicio,name='UpdateFNExercicio'),
	path('desabilitar/nao-exercicio/funcionario/index.html?fid=<str:id>&idfne=<str:idfne>&desabilitar=True',DesabilitarFNExercicio,name='DesabilitarFNExercicio'),
	
	path('lista/saida/funcionario/index.html?fid=<str:id>&lista=True',DetalhoFuncionarioListaSaida,name='DetalhoFuncionarioListaSaida'),
	path('registar/saida/funcionario/index.html?fid=<str:id>&registar=True',DetalhoFuncionarioRegistarFSaida,name='DetalhoFuncionarioRegistarFSaida'),
	path('alterar/saida/funcionario/index.html?fid=<str:id>&idfsd=<str:idfsd>&alterar=True',DetalhoFuncionarioAlterarFSaida,name='DetalhoFuncionarioAlterarFSaida'),
	path('desabilitar/saida/funcionario/index.html?fid=<str:id>&idfsd=<str:idfsd>&desabilitar=True',DesabilitarFSaida,name='DesabilitarFSaida'),
	

	path('busca-funcionario/', BuscaFuncionario, name='BuscaFuncionario'),

	# path('imajen/upload/funcionario/index.html?fid=<str:fid>&upload-image=True',updatedImageFun,name='updatedImageFun'),
	path('imajen/upload/funcionario/index.html/fid=<str:fid>',updatedImageFun1,name='updatedImageFun1'),
]

hrms/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from master.views import loginPage,logout_view
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/sgrh/', admin.site.urls),
    path('login/', loginPage, name='login'),
    path('logout/', logout_view, name='logout'),
    path('', include('master.urls')),
    path('gutilizador/', include('gutilizador.urls')),
    path('gfuncionarios/', include('gfuncionarios.urls')),
    path('gdivisao_administrativa/', include('gdivisao_administrativa.urls')),
    path('gcarreira/', include('gcarreira.urls')),
    path('funcao/', include('funcao.urls')),
    path('gavaliacao_desempenho/', include('gavaliacao_desempenho.urls')),
    path('ministerio/', include('unidade_ministerio.urls')),
    path('reports/', include('reports.urls')),
    path('habilitacao/', include('habilitacao.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = "SGRH-ME - Sistema Gestao Recursos Humanos-ME - SUPER USER"
admin.site.site_title = "SGRH-ME - Sistema Gestao Recursos Humanos-ME - SUPER USER"
admin.site.index_title = "Pajina Super User"

gfuncionarios/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
import uuid
import datetime
from gdivisao_administrativa.models import *
from unidade_ministerio.models import *
from funcao.models import *
from django.utils import timezone
now = timezone.now()
from django.db.models import Q
from datetime import date

# Create your models here.
class Funcionarios(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	nome = models.CharField(max_length=225, null=True, blank=True)
	sexo = models.CharField(choices=[('Masculino','Masculino'),('Feminino','Feminino')], max_length=15,default='Masculino')
	id_sigap = models.CharField(max_length=30, null=True, blank=True)
	id_grp = models.CharField(max_length=50, verbose_name='Id GRP', null=True, blank=True)
	data_nascimento = models.DateField(verbose_name='Data de Nascimento',default='1970-01-01')
	lugar_nascimento = models.CharField(max_length=50, null=True, blank=True)
	nu_telemovel = models.CharField(max_length=50, null=True, blank=True)
	nu_emis = models.CharField(max_length=50, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	nss = models.CharField(max_length=50, null=True, blank=True)
	nu_eleitoral = models.CharField(max_length=50, null=True, blank=True)
	data_emissao_eleitoral = models.DateField(verbose_name='Data Emissao Eleitoral', null=True, blank=True)
	nu_bi = models.CharField(max_length=50, null=True, blank=True)
	data_validade_bi = models.DateField(verbose_name='Data Validade BI', null=True, blank=True)
	nu_conducao = models.CharField(max_length=50, null=True, blank=True)
	tipo_conducao = models.CharField(max_length=50, null=True, blank=True)
	data_validade_conducao = models.DateField(verbose_name='Data Validade Carta Conducao', null=True, blank=True)
	nome_pai = models.CharField(max_length=100, null=True, blank=True)
	nome_mae = models.CharField(max_length=100, null=True, blank=True)
	code_vendor = models.CharField(max_length=100, null=True, blank=True)
	controlo_ativo = models.CharField(choices=[('Ativo','Ativo'),('Não Exercício','Não Exercício'),('Saída Definitiva','Saída Definitiva')], max_length=40,default='Ativo')

	inserido_em = models.DateTimeField(auto_now_add=True,null=True,blank=True)
	inserido_por = models.CharField(max_length=50, verbose_name='Inserido por', null=True, blank=True)
	alterado_em = models.DateTimeField(auto_now_add=False,null=True,blank=True)
	alterado_por = models.CharField(max_length=50, verbose_name='Alterado por', null=True, blank=True)

	def getidade(self):
		if self.data_nascimento:
			return datetime.date.today().year - self.data_nascimento.year
		else:
			return 0

	def getImagemPessoal(self):
		imagem = ImagemPessoal.objects.get(pessoa=self)
		return imagem.dados

	def getColocacao(self):
		objects = Ficha_colocacao.objects.filter(funcionario=self,data_fim__isnull=True).order_by('-data_inicio').last() 
		return objects

	def getContratacao(self):
		objects = Ficha_contratacao.objects.filter(funcionario=self,data_fim__gte=now).exclude(controlo_estado='Desabilitar').last() 
		return objects

	def getPermanente(self):
		objects = Ficha_permanente.objects.filter(funcionario=self,data_fim__isnull=True).exclude(controlo_estado='Desabilitar').last() 
		return objects

	def getFNE(self):
		objects = Ficha_nao_exercicio.objects.filter(funcionario=self).exclude(controlo_estado='Desabilitar').filter(Q(data_fim__isnull=True)|Q(data_fim__gt=date.today())).last() 
		return objects
	def getFSD(self):
		objects = Ficha_saida_definitiva.objects.filter(funcionario=self).exclude(controlo_estado='Desabilitar').order_by('-data_saida').first() 
		return objects
	

	class Meta:
		db_table = 'sgrh"."gfuncionarios'

	def __str__(self):
		template = '{0.nome}, {0.id_sigap}'
		return template.format(self)


# Model for arquivos
class ImagemPessoal(models.Model):
	id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	pessoa = models.OneToOneField(Funcionarios, on_delete=models.CASCADE,related_name="imagemfuncionario")
	dados = models.TextField()
	class Meta:
		db_table = 'arquivos"."binario_funcionario'  # Note the schema and table name



class Tipo_colocacao(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    tipo = models.CharField(max_length=100, null=True, blank=True)
    controlo_estado = models.CharField(max_length=50, null=True, blank=True)

    inserido_em = models.DateTimeField(auto_now_add=True,null=True,blank=True)
    inserido_por = models.CharField(max_length=50, verbose_name='Inserido por', null=True, blank=True)
    alterado_em = models.DateTimeField(auto_now_add=False,null=True,blank=True)
    alterado_por = models.CharField(max_length=50, verbose_name='Alterado por', null=True, blank=True)

    class Meta:
        db_table = 'sgrh"."tipo_colocacao'

    def __str__(self):
        template = '{0.tipo} '
        return template.format(self)





class Ficha_colocacao(models.Model):
	id_colocacao = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
	funcionario = models.ForeignKey(Funcionarios, on_delete=models.CASCADE,related_name='colocacaoFuncionario')
	dg = models.ForeignKey('unidade_ministerio.Direcao_geral', on_delete=models.CASCADE,null=True)
	dn = models.ForeignKey('unidade_ministerio.Direcao_nacional', on_delete=models.CASCADE,null=True)
	dep = models.ForeignKey('unidade_ministerio.Departamento', on_delete=models.CASCADE,null=True)
	sec = models.ForeignKey('unidade_ministerio.Seccao', on_delete=models.CASCADE,null=True)
	local_trabalho = models.ForeignKey(Gdivisao_administrativa_municipio, on_delete=models.CASCADE)
	tipo_colocacao = models.ForeignKey(Tipo_colocacao, on_delete=models.CASCADE)
	data_inicio = models.DateField(verbose_name='Data Inicio', null=True, blank=True)
	data_fim = models.DateField(verbose_name='Data Fim', null=True, blank=True)
	controlo_estado = models.CharField(max_length=50, null=True, blank=True)

	inserido_em = models.DateTimeField(auto_now_add=True,null=True,blank=True)
	inserido_por = models.CharField(max_length=50, verbose_name='Inserido por', null=True, blank=True)
	alterado_em = models.DateTimeField(auto_now_add=False,null=True,blank=True)
	alterado_por = models.CharField(max_length=50, verbose_name='Alterado por', null=True, blank=True)

	class Meta:
		db_table = 'sgrh"."colocacao'

	def __str__(self):
		template = '{0.funcionario}'
		return template.format(self)





# views

class ListaFuncionarioCompleto(models.Model):
	id = models.UUIDField(primary_key=True)
	nome = models.CharField(max_length=225, null=True, blank=True)
	sexo = models.CharField(choices=[('Masculino','Masculino'),('Feminino','Feminino')], max_length=15,default='Masculino')
	id_sigap = models.CharField(max_length=30, null=True, blank=True)
	id_grp = models.CharField(max_length=50, verbose_name='Id GRP', null=True, blank=True)
	data_nascimento = models.DateField(verbose_name='Data de Nascimento',default='1970-01-01')
	lugar_nascimento = models.CharField(max_length=50, null=True, blank=True)
	nu_telemovel = models.CharField(max_length=50, null=True, blank=True)
	nu_emis = models.CharField(max_length=50, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	nss = models.CharField(max_length=50, null=True, blank=True)
	nu_eleitoral = models.CharField(max_length=50, null=True, blank=True)
	data_emissao_eleitoral = models.DateField(verbose_name='Data Emissao Eleitoral', null=True, blank=True)
	nu_bi = models.CharField(max_length=50, null=True, blank=True)
	data_validade_bi = models.DateField(verbose_name='Data Validade BI', null=True, blank=True)
	nu_conducao = models.CharField(max_length=50, null=True, blank=True)
	tipo_conducao = models.CharField(max_length=50, null=True, blank=True)
	data_validade_conducao = models.DateField(verbose_name='Data Validade Carta Conducao', null=True, blank=True)
	nome_pai = models.CharField(max_length=100, null=True, blank=True)
	nome_mae = models.CharField(max_length=100, null=True, blank=True)
	code_vendor = models.CharField(max_length=100, null=True, blank=True)
	controlo_ativo = models.CharField(choices=[('Ativo','Ativo'),('Não Exercício','Não Exercício'),('Saída Definitiva','Saída Definitiva')], max_length=40,default='Ativo')

	inserido_em = models.DateTimeField(auto_now_add=True,null=True,blank=True)
	inserido_por = models.CharField(max_length=50, verbose_name='Inserido por', null=True, blank=True)
	alterado_em = models.DateTimeField(auto_now_add=False,null=True,blank=True)
	alterado_por = models.CharField(max_length=50, verbose_name='Alterado por', null=True, blank=True)
	dados_imajen = models.TextField()
	idade = models.IntegerField()


	class Meta:
		managed = False
		db_table = 'sgrh"."viewlistafuncionariofompleto'

	

class ListaFuncionarioCompleto1(models.Model):
	id = models.UUIDField(primary_key=True)
	nome = models.CharField(max_length=225, null=True, blank=True)
	sexo = models.CharField(choices=[('Masculino','Masculino'),('Feminino','Feminino')], max_length=15,default='Masculino')
	id_sigap = models.CharField(max_length=30, null=True, blank=True)
	id_grp = models.CharField(max_length=50, verbose_name='Id GRP', null=True, blank=True)
	data_nascimento = models.DateField(verbose_name='Data de Nascimento',default='1970-01-01')
	lugar_nascimento = models.CharField(max_length=50, null=True, blank=True)
	nu_telemovel = models.CharField(max_length=50, null=True, blank=True)
	nu_emis = models.CharField(max_length=50, null=True, blank=True)
	email = models.CharField(max_length=100, null=True, blank=True)
	nss = models.CharField(max_length=50, null=True, blank=True)
	nu_eleitoral = models.CharField(max_length=50, null=True, blank=True)
	data_emissao_eleitoral = models.DateField(verbose_name='Data Emissao Eleitoral', null=True, blank=True)
	nu_bi = models.CharField(max_length=50, null=True, blank=True)

gfuncionarios/templates/funcionario/detalho.html
{% extends 'main/base.html' %}
{% load static %}
{% block content %}
<!--begin::Post-->
<div class="post d-flex flex-column-fluid" id="kt_post">
	<!--begin::Container-->
	<div id="kt_content_container" class="container-xxl">
		<!--begin::Row-->
		{% include 'funcionario/head_detalho_funcionario.html' %}
		<div class="row gy-5 g-xl-8">
			<!--begin::Col-->
			<div class="col-xl-12">
				<div class="card p-5">
					<!--begin::Header-->
					<div class="border-0 pt-0">
						<h3 class=" align-items-start flex-column">
							<!-- <span class="card-label fw-bolder fs-3 mb-1">Lista Utilizador</span> -->
							<span class="text-muted mt-1 fw-bold fs-4">
							{% if page == 'alterar_fun' %}
							Alterar Dados - {{objects.nome}}
							{% elif page == 'detalho_fun' %}
							Detalho - {{objects.nome}}
							{% elif page == 'detalho_funcionario_lista_funcao' %}
							Lista Função - {{objects.nome}}
							{% else %}
							{{title}}
							{% endif %}
							</span>
						</h3>
						
					</div>
					<!--end::Header-->
					<!--begin::Body-->
						<!--begin::Table container-->
						
						
						<!--end::Table container-->
					
				</div>
				{% block content_funcionario_detail_tab %}
				{% endblock %}
				{% if page == 'detalho_fun' %}
					<div class="bg-white p-2 d-flex justify-content-end">
						<a href="{% url 'AtualizarFuncionario' objects.id %}" class="mx-2 btn btn-sm btn-light-primary btn-active-primary" >
						<i class="bi bi-pencil-square"></i>Atualizar</a>
						<a href="#" data-bs-toggle="modal" data-bs-target="#desabilitar_funcionario_{{objects.id}}" class="btn btn-sm btn-light-danger btn-active-danger" >
						<i class="bi bi-trash"></i>Desabilitar</a>
						<!-- {% if page == 'detalho_funcionario_lista_funcao' %}
						<a href="{% url 'AtualizarFuncionario' objects.id %}" class="btn btn-sm btn-light-primary btn-active-primary" >
						<i class="bi bi-plus-square"></i>Inserir Novo Função</a>
						{% endif %} -->
					</div>
				{% endif %}
			</div>
			<!--end::Col-->
		</div>
	</div>
</div>



<!-- modal -->
<div class="modal fade" id="desabilitar_funcionario_{{objects.id}}" tabindex="-1">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
            <div class="col-12 text-center">
            	<img src="{% static 'img/danger_alert_img.png' %}" height="150px">
            	<h3>
            	Você tem certeza para desabilitar esse dados?
            	</h3>
            	<p>você não pode reverter dados de {{objects.nome}}!</p>
            </div>
            <div class="d-flex justify-content-center mt-5">
              <button data-bs-dismiss="modal" type="button" class="btn btn-lg btn-secondary mx-3">Não</button>
              <a href="{% url 'DesabilitarFuncionario' objects.id %}" class="btn btn-lg btn-primary">Sim</a>
            </div>
        </div>
      </div>
    </div>
</div><!-- End Vertically centered Modal-->


{% endblock %}

{% block modal %}
{% endblock %}

gfuncionarios/templates/funcionario/form.html
{% extends 'main/base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content %}
<!--begin::Post-->
<div class="post d-flex flex-column-fluid" id="kt_post">
	<!--begin::Container-->
	<div id="kt_content_container" class="container-xxl">
		<!--begin::Row-->
		<div class="row gy-5 g-xl-8">
			<!--begin::Col-->
				<div class="card p-5">
					<div class="card-header"><h2>Formulario {{title}}</h2></div>
					<div class="card-body p-9">
						{% if form %}
						{% csrf_token %}
						    {% crispy form %}
						{% else %}
						    <p>Form object is None or not available.</p>
						{% endif %}

					</div>
					
				</div>
			<!--end::Col-->
		</div>
	</div>
</div>
<script type="text/javascript">
  //load Imagen
    function myFunction() {
      var image = document.getElementById("output");
      image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>


{% endblock %}

{% block modal %}
{% endblock %}

gfuncionarios/templates/funcionario/form_tab.html
{% extends 'funcionario/detalho.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block content_funcionario_detail_tab %}

<div class="card">
<div class="card-body">
	
						{% if form %}
						{% csrf_token %}
						    {% crispy form %}
						{% else %}
						    <p>Form object is None or not available.</p>
						{% endif %}

</div>
</div>
					
<script type="text/javascript">
  //load Imagen
    function myFunction() {
      var image = document.getElementById("output");
      image.src = URL.createObjectURL(event.target.files[0]);
    }
</script>

{% if page == 'form_funcao_fun' %}

<script>
document.getElementById("tipo-alteracao-ficha-select").addEventListener("change", function() {
    const regimeId = this.value;
    const id_fun = '{{objects.id}}';
    console.log("regimeId:"+regimeId);
    console.log("id_fun:"+id_fun);
    const relacaoJuridicaEmpregoField = document.getElementById("relacao-juridica-select");
    if (regimeId === 'dfbbdad5-90d7-4507-aac1-7085ea558216') {
        // Hide the relacao_juridica_emprego input
        relacaoJuridicaEmpregoField.disabled = true;
        // relacaoJuridicaEmpregoField.style.display = "none";
    } else {
        // Show the relacao_juridica_emprego input
        relacaoJuridicaEmpregoField.disabled = false;
        // relacaoJuridicaEmpregoField.style.display = "block";
    }
    // if (regimeId == 'dfbbdad5-90d7-4507-aac1-7085ea558216') {

    // fetch(`/funcao/ajax/load-form-progrssao/?id_tipo_alteracao_ficha=${regimeId}&id_fun=${id_fun}`)
    //     .then(response => response.json())
    //     .then(data => {
    //         const relacao_juridicaSelect = document.getElementById("relacao-juridica-select");
    //         // relacao_juridicaSelect.innerHTML = '<option value="">Select relacao_juridica</option>';
    //         data.forEach(relacao_juridica => {
    //             relacao_juridicaSelect.innerHTML += `<option value="${relacao_juridica.id_relacao_juridica_emprego}">${relacao_juridica.relacao_juridica_emprego}</option>`;
    //         });
    //     });
    // }
});

document.getElementById("regime-select").addEventListener("change", function() {
    const regimeId = this.value;
    fetch(`/funcao/ajax/load-categorias/?regime_id=${regimeId}`)
        .then(response => response.json())
        .then(data => {
            const categoriaSelect = document.getElementById("categoria-select");
            categoriaSelect.innerHTML = '<option value="">Select Categoria</option>';
            data.forEach(categoria => {
                categoriaSelect.innerHTML += `<option value="${categoria.id_categoria}">${categoria.categoria}</option>`;
            });
        });
});

document.getElementById("categoria-select").addEventListener("change", function() {
    const categoriaId = this.value;
    fetch(`/funcao/ajax/load-escalaos/?categoria_id=${categoriaId}`)
        .then(response => response.json())
        .then(data => {
            const escalaoSelect = document.getElementById("escalao-select");
            escalaoSelect.innerHTML = '<option value="">Select Escalao</option>';
            data.forEach(escalao => {
                escalaoSelect.innerHTML += `<option value="${escalao.id_escalao}">${escalao.escalao}</option>`;
            });
        });
});

document.getElementById("escalao-select").addEventListener("change", function() {
    const escalaoId = this.value;
    fetch(`/funcao/ajax/load-indices/?escalao_id=${escalaoId}`)
        .then(response => response.json())
        .then(data => {
            const indiceSelect = document.getElementById("indice-select");
            indiceSelect.innerHTML = '<option value="">Select Indice</option>';
            data.forEach(indice => {
                indiceSelect.innerHTML += `<option value="${indice.id_indice}">${indice.indice}</option>`;
            });
        });
});
</script>


{% endif %}

{% if page == 'form_funcao_fun_casual' %}
<script type="text/javascript">
    document.getElementById("regime-select").addEventListener("change", function() {
    const regimeId = this.value;
    fetch(`/funcao/ajax/load-categorias/?regime_id=${regimeId}`)
        .then(response => response.json())
        .then(data => {
            const categoriaSelect = document.getElementById("categoria-select");
            categoriaSelect.innerHTML = '<option value="">Select Categoria</option>';
            data.forEach(categoria => {
                categoriaSelect.innerHTML += `<option value="${categoria.id_categoria}">${categoria.categoria}</option>`;
            });
        });
});

document.getElementById("categoria-select").addEventListener("change", function() {
    const categoriaId = this.value;
    fetch(`/funcao/ajax/load-escalaos/?categoria_id=${categoriaId}`)
        .then(response => response.json())
        .then(data => {
            const escalaoSelect = document.getElementById("escalao-select");
            escalaoSelect.innerHTML = '<option value="">Select Escalao</option>';
            data.forEach(escalao => {
                escalaoSelect.innerHTML += `<option value="${escalao.id_escalao}">${escalao.escalao}</option>`;
            });
        });
});

document.getElementById("escalao-select").addEventListener("change", function() {
    const escalaoId = this.value;
    fetch(`/funcao/ajax/load-indices/?escalao_id=${escalaoId}`)
        .then(response => response.json())
        .then(data => {
            const indiceSelect = document.getElementById("indice-select");
            indiceSelect.innerHTML = '<option value="">Select Indice</option>';
            data.forEach(indice => {
                indiceSelect.innerHTML += `<option value="${indice.id_indice}">${indice.indice}</option>`;
            });
        });
});
</script>
{% endif %}

{% if page == 'form_colocacao_fun' %}
<script src="{% static 'assets/js/jquery.min.js'%}"> </script>
<script>
	$("#id_dg").change(function () {
        var dgID = $(this).val();
        // console.log("postId:" + postId);
        $.ajax({
            url: "{% url 'ajax_load_dir_nac' %}",
            data: {
                'dg': dgID
            },
            success: function (data) {
                $("#id_dn").html(data);
            }
        });
    });

	$("#id_dg").change(function () {
        var dgID = $(this).val();
        // console.log("postId:" + postId);
        $.ajax({
            url: "{% url 'ajax_load_escola_dg' %}",
            data: {
                'dg': dgID
            },
            success: function (data) {
                $("#id_escola").html(data);
            }
        });
    });

    $("#id_dn").change(function () {
        var dnID = $(this).val();
        // console.log("postId:" + postId);
        $.ajax({
            url: "{% url 'ajax_load_departamento' %}",
            data: {
                'id': dnID
            },
            success: function (data) {
                $("#id_dep").html(data);
            }
        });
    });
    $("#id_dep").change(function () {
        var depID = $(this).val();
        // console.log("postId:" + postId);
        $.ajax({ 
            url: "{% url 'ajax_load_seccao' %}",
            data: {
                'id': depID
            },
            success: function (data) {
                $("#id_sec").html(data);
            }
        });
    });
</script>


{% endif %}


{% endblock %}

{% block modal %}
{% endblock %}